spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobportal
    username: root
    password: mysql4677

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
server:
  servlet:
    session:
      persistent: false